- name: Install basic dependencies for Kubernetes
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - containerd
    - curl
    state: present
  tags:
  - packages

# TODO: containerd setup
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

- name: Download Google Cloud public signing key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes apt repository
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
  notify: Update apt cache

- name: Flush handlers
  meta: flush_handlers

- name: Install Kubernetes packages
  apt:
    name:
    - kubelet
    - kubeadm
    - kubectl
    state: present
  tags:
  - packages

# TODO: may need to disable swap
# swapoff -a

- name: Install modules-load.d/containerd.conf
  copy:
    src: modules-load.d/containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: Install sysctl.d/99-kubernetes-cri.conf
  copy:
    src: sysctl.d/99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  notify: Reload sysctl

# -> need to sure IPv6 forwarding is enabled too (with accept_ra=2)

#- name: Create containerd config directory
#  file:
#    dest: /etc/containerd
#    state: directory

#- name: Install containerd config
#  copy:
#    src: containerd/config.toml
#    dest: /etc/containerd/config.toml
#  notify: Restart containerd

- name: Flush handlers
  meta: flush_handlers

- name: Start containerd
  service:
    name: containerd.service
    state: started
