---
- name: Install Python dependencies
  yum: pkg={{ item }} state=present
  with_items:
  - gcc
  - python-pip
  - python-devel
  tags:
  - packages
  - elastalert

- name: Use pip to upgrade pip and setuptools
  pip: name={{ item }} state=latest
  with_items:
  - pip
  - setuptools
  tags:
  - packages
  - elastalert

- name: Install elastalert
  pip: name=elastalert state=present
  tags:
  - packages
  - elastalert

- name: Install ircalert binary
  copy: src=ircalert dest=/usr/local/bin/ircalert mode=0755

- name: Create elastalert config directories
  file: dest=/etc/{{ item }} state=directory
  with_items:
  - elastalert
  - elastalert/rules
  tags:
  - elastalert

# elastalert-create-index

- name: Install elastalert config
  copy:
    src: elastalert/config.yaml
    dest: /etc/elastalert/config.yaml
  tags:
  - elastalert

- name: Install elastalert rules
  template:
    src: elastalert/rules/{{ item }}.j2
    dest: /etc/elastalert/rules/{{ item }}
  with_items:
  - nginx_5xx.yaml
  - sshd_backup_login.yaml
  - sshd_root_login.yaml
  - website_exception.yaml
  tags:
  - elastalert

- name: Create a group for elastalert
  group: name=elastalert system=yes state=present
  tags:
  - elastalert

- name: Create a user for elastalert
  user: name=elastalert group=elastalert home=/var/lib/elastalert
        shell=/bin/false system=yes state=present
  tags:
  - elastalert

- name: Install elastalert.service
  copy: src=elastalert/elastalert.service
        dest=/etc/systemd/system/elastalert.service
  tags:
  - elastalert

- name: Start and enable elastalert
  service: name=elastalert state=started enabled=yes
  tags:
  - services
  - elastalert
