---
- name: Install johnny-six config
  template:
    src: johnny-six.j2
    dest: /etc/default/johnny-six
    mode: 0600

- name: Import johnny-six service
  copy:
    src: johnny-six.service
    dest: /etc/systemd/system/johnny-six.service

- name: Start and enable johnny-six service
  service:
    name: johnny-six
    state: started
    enabled: yes

#- name: Install underwriting cronjob
#  cron:
#    name: johnny-six underwriting
#    user: liquidsoap
#    minute: 55
#    job: python3 /opt/johnny-six/queue_underwriting.py
#    state: present
