- name: Create /mnt/automation
  file:
    dest: /mnt/automation
    state: directory

- name: Set up /mnt/automation mount
  mount:
    name: /mnt/automation
    src: alexandria.wuvt.vt.edu:/tank/automation
    fstype: nfs
    opts: sec=krb5p
    state: mounted

- import_tasks: packages.yml
- import_tasks: docker.yml

- name: Add liquidsoap user to audio group
  user:
    name: liquidsoap
    groups: liquidsoap,audio

- import_tasks: johnnysix.yml
