stream_generator_alsa_input: "plughw:CARD=USB,DEV=0"

stream_host: "localhost"
stream_port: 8000
stream_password: "hackme"

stream_meta_name: "WUVT-FM 90.7 Blacksburg, VA"
stream_meta_description: "The greatest radio station in the world"
stream_meta_genre: "College radio"
stream_meta_url: "https://www.wuvt.vt.edu"
stream_mount_prefix: "wuvt"
