- hosts: centos
  become: yes
  handlers:
  - import_tasks: handlers/mail.yml
  vars_files:
  - vars/mail.yml
  - vars/freeipa_private.yml
  roles:
  - centos-common
  - common
  - osquery
  - freeipa-client
  - log-forwarder
