- hosts: etcd-server
  become: yes
  vars_files:
  - vars/container.yml
  - vars/container_private.yml
  gather_facts: false
  roles:
  - etcd-server

- hosts: kubernetes-controller
  become: yes
  vars:
    locksmith_window_start: 06:00
    locksmith_window_length: 1h
  vars_files:
  - vars/container.yml
  - vars/container_private.yml
  gather_facts: false
  roles:
  - kubernetes-controller

- hosts: kubernetes-worker
  become: yes
  vars:
    locksmith_window_start: 06:00
    locksmith_window_length: 1h
  vars_files:
  - vars/container.yml
  - vars/container_private.yml
  gather_facts: false
  roles:
  - kubernetes-worker
