- hosts: etcd_server:kubernetes_controller_legacy:kubernetes_worker_legacy
  vars_files:
  - vars/cfssl.yml
  - vars/container.yml
  gather_facts: false
  tasks:
  - name: Generate certificate
    shell: cfssl genkey - <<< {{ cfssl_request | to_json | quote }} | cfssljson -bare {{ hostname }}
    args:
      chdir: "{{ pki_dir }}"
      creates: "{{ hostname }}.csr"
    delegate_to: localhost

  - name: Sign certificate
    cfssl_sign:
      endpoint: "{{ cfssl_endpoint }}"
      endpoint_ca: "{{ cfssl_endpoint_ca }}"
      csr: "{{ pki_dir }}{{ hostname }}.csr"
      dest: "{{ pki_dir }}{{ hostname }}.pem"
      auth_key: "{{ cfssl_auth_key_cluster }}"
      label: cluster
    delegate_to: localhost

- hosts: etcd_server
  become: yes
  vars_files:
  - vars/container.yml
  - vars/container_private.yml
  gather_facts: false
  roles:
  - etcd-server

- hosts: kubernetes_controller_legacy
  become: yes
  vars_files:
  - vars/container.yml
  - vars/container_private.yml
  gather_facts: false
  roles:
  - kubernetes-controller

- hosts: kubernetes_worker_legacy
  become: yes
  vars_files:
  - vars/container.yml
  - vars/container_private.yml
  gather_facts: false
  roles:
  - kubernetes-worker
