- hosts: database
  become: yes
  roles:
  - dbserver
  vars_files:
  - vars/postgres_private.yml
  - vars/typesense_private.yml
  - vars/pgbackup_private.json
  vars:
    ansible_remote_tmp: /tmp/ansible-tmp