- hosts: fileserver
  become: yes
  roles:
  - osquery
  - freeipa-client
  - webserver
  - backupserver
  - file
  vars_files:
  - vars/freeipa_private.yml
  - vars/internetarchive_private.yml
  - vars/pgbackup_private.json
  - vars/zpool_healthcheck_private.yml