- hosts: localhost
  vars_files:
  - vars/cfssl.yml
  - vars/container.yml
  gather_facts: false
  tasks:
  - name: Sign certificate
    cfssl_sign:
      endpoint: "{{ cfssl_endpoint }}"
      endpoint_ca: "{{ cfssl_endpoint_ca }}"
      csr: "files/upstream_pki/{{ item }}.csr"
      dest: "files/upstream_pki/{{ item }}.pem"
      auth_key: "{{ cfssl_auth_key_root }}"
      label: root
    with_items:
    - wuvt-site-am
    - wuvt-site-prod
    - dex
    - trackman-am
    - trackman-fm
    - logstash
    - wuvt-site-stg
    - trackman-stg
    - sso-auth
    - sso-proxy
