- hosts: dreyfus.wuvt.vt.edu
  gather_facts: false
  tasks:
  - name: Update wuvt-site git repo
    raw: pushd wuvt-site && git pull && popd
    tags:
    - build

  - name: Build wuvt-site container
    raw: docker build -t registry.wuvt.vt.edu/wuvt-site -f wuvt-site/Dockerfile.prod wuvt-site
    tags:
    - build

  - name: Push wuvt-site container to registry
    raw: docker push registry.wuvt.vt.edu/wuvt-site
    tags:
    - build

  - name: Roll out wuvt-site updates
    script: site_rollout.sh
    tags:
    - rollout
