filebeat:
  prospectors:
    -
      paths:
        - "/var/log/containers/*.log"
      document_type: kubernetes
output:
  logstash:
    hosts: ["192.168.0.223:5043"]
    tls:
      certificate_authorities: ["/etc/filebeat/logstash.pem"]
    index: filebeat
