---
etcd_initial_cluster_token: etcd-cluster-1
etcd_discovery_srv: wuvt.vt.edu
nginx_ocsp_stapling: true
nginx_sites:
- am.wuvt.vt.edu
- default
- jira.wuvt.vt.edu
#- lists.wuvt.vt.edu
- musicbrainz.apps.wuvt.vt.edu
- registry.wuvt.vt.edu
- www.wuvt.vt.edu
