- name: Create cloud-config directory
  file:
    dest: /var/lib/libvirt/images/coreos/{{ hostname }}/openstack/latest
    state: directory
    mode: 0700
    owner: "{{ qemu_user | default('qemu') }}"
    group: "{{ qemu_group | default('qemu') }}"
  delegate_to: "{{ hypervisor }}"

- name: Install cloud-config file
  template:
    src: cloud-config.yaml.j2
    dest: /var/lib/libvirt/images/coreos/{{ hostname }}/openstack/latest/user_data
  delegate_to: "{{ hypervisor }}"

- name: Build config drive ISO (for use when virtfs is not available)
  command: /usr/bin/mkisofs -R -V config-2 -o "/var/lib/libvirt/images/coreos/{{ hostname }}_configdrive.iso" /var/lib/libvirt/images/coreos/{{ hostname }}
  delegate_to: "{{ hypervisor }}"

- name: Define libvirt guest
  virt:
    name: "{{ hostname }}"
    command: define
    xml: "{{ lookup('template', 'domain.xml.j2') }}"
    uri: qemu:///system
  delegate_to: "{{ hypervisor }}"
