- name: Update ignition_extra_files
  set_fact:
    ignition_extra_files: "{{ ignition_role_files + ignition_extra_files }}"
  when:
    ignition_role_files is defined

- name: Update ignition_extra_services
  set_fact:
    ignition_extra_services: "{{ ignition_role_services + ignition_extra_services }}"
  when:
    ignition_extra_services is defined

- name: Create guest image data directory
  file:
    dest: /var/lib/libvirt/images/coreos/{{ hostname }}
    state: directory
    mode: 0700
    owner: qemu
    group: qemu
  delegate_to: "{{ hypervisor }}"

- name: Install ignition.json
  template:
    src: ignition.json.j2
    dest: /var/lib/libvirt/images/coreos/{{ hostname }}/ignition.json
    mode: 0600
    owner: qemu
    group: qemu
  delegate_to: "{{ hypervisor }}"

- name: Create cloud-config directory
  file:
    dest: /var/lib/libvirt/images/coreos/{{ hostname }}/openstack/latest
    state: directory
    mode: 0700
    owner: qemu
    group: qemu
  delegate_to: "{{ hypervisor }}"

- name: Install cloud-config file
  template:
    src: cloud-config.yaml.j2
    dest: /var/lib/libvirt/images/coreos/{{ hostname }}/openstack/latest/user_data
  delegate_to: "{{ hypervisor }}"

- name: Build config drive ISO (for use when virtfs is not available)
  command: /usr/bin/mkisofs -R -V config-2 -o "/var/lib/libvirt/images/coreos/{{ hostname }}_configdrive.iso" /var/lib/libvirt/images/coreos/{{ hostname }}
  delegate_to: "{{ hypervisor }}"

- name: Create guest disk image
  command: /usr/bin/qemu-img create -f qcow2 -b coreos_production_qemu_image.img {{ hostname }}.qcow2 80G
  args:
    chdir: /var/lib/libvirt/images/coreos
    creates: /var/lib/libvirt/images/coreos/{{ hostname }}.qcow2
  become: yes
  become_user: qemu
  delegate_to: "{{ hypervisor }}"

- name: Install libvirt-python
  yum: name=libvirt-python state=present
  delegate_to: "{{ hypervisor }}"

- name: Define libvirt guest
  virt:
    name: "{{ hostname }}"
    command: define
    xml: "{{ lookup('template', 'domain.xml.j2') }}"
    uri: qemu:///system
  delegate_to: "{{ hypervisor }}"

# FIXME: doesn't work if domain is already running
#- name: Start libvirt guest
#  virt:
#    name: "{{ hostname }}"
#    command: start
#  delegate_to: "{{ hypervisor }}"
