- name: Update ignition_extra_files
  set_fact:
    ignition_extra_files: "{{ ignition_role_files + ignition_extra_files }}"
  when:
    ignition_role_files is defined

- name: Update ignition_extra_services
  set_fact:
    ignition_extra_services: "{{ ignition_role_services + ignition_extra_services }}"
  when:
    ignition_extra_services is defined

- name: Install libvirt-python (apt)
  apt: name=python-libvirt state=present
  delegate_to: "{{ hypervisor }}"
  when: use_apt

- name: Install libvirt-python (yum)
  yum: name=libvirt-python state=present
  delegate_to: "{{ hypervisor }}"
  when: not use_apt

- name: Create guest image data directory
  file:
    dest: /var/lib/libvirt/images/coreos/{{ hostname }}
    state: directory
    mode: 0700
    owner: "{{ qemu_user }}"
    group: "{{ qemu_group }}"
  delegate_to: "{{ hypervisor }}"

- name: Create guest disk image
  command: /usr/bin/qemu-img create -f qcow2 -b coreos_production_qemu_image.img {{ hostname }}.qcow2 80G
  args:
    chdir: /var/lib/libvirt/images/coreos
    creates: /var/lib/libvirt/images/coreos/{{ hostname }}.qcow2
  become: yes
  become_user: "{{ qemu_user }}"
  delegate_to: "{{ hypervisor }}"

- include_tasks: ignition.yml
  when: use_ignition

- include_tasks: cloudconfig.yml
  when: not use_ignition

# FIXME: doesn't work if domain is already running
#- name: Start libvirt guest
#  virt:
#    name: "{{ hostname }}"
#    command: start
#  delegate_to: "{{ hypervisor }}"
