- name: Configure icecast.xml
  template: src=icecast.xml.j2 dest=/etc/icecast.xml mode=0660
  tags:
  - configure
  - stream
- name: Stop icecast service
  service: name=icecast state=stopped
  tags:
  - configure
  - stream
- name: Enable icecast service
  service: name=icecast enabled=yes
  tags:
  - configure
  - stream
- name: Start icecast service
  service: name=icecast state=started
  tags:
  - configure
  - stream
