etcd_files:
- filesystem: root
  path: /etc/ssl/etcd/ca.pem
  mode: 420
  user: etcd
  group: etcd
  contents:
    source: "data:,{{ lookup('file', pki_dir + 'ca.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/ssl/etcd/{{ hostname }}.pem
  mode: 420
  user: etcd
  group: etcd
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/ssl/etcd/{{ hostname }}-key.pem
  mode: 384
  user: etcd
  group: etcd
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '-key.pem') | replace('\n', '\\n') }}"

etcd_services:
- name: locksmithd.service
  enable: true
  dropins:
  - name: 20-etcd.conf
    contents: "{{ lookup('template', 'systemd/system/locksmithd.service.d/20-etcd.conf.j2') | replace('\n', '\\n') }}"
- name: etcd-member.service
  enable: true
  dropins:
  - name: 20-cluster.conf
    contents: "{{ lookup('template', 'systemd/system/etcd-member.service.d/20-cluster.conf.j2') | replace('\n', '\\n') }}"
