name: Use of backup account by unexpected client
type: frequency
index: syslog-*

num_events: 1
timeframe:
  minutes: 10

filter:
- query:
    query_string:
      query: "tags:login AND NOT tags:pam AND user.raw:backup AND NOT clientip:192.168.0.55 AND NOT clientip:192.168.0.203"

alert:
- "email"
- "command"
email:
- "wuvt.it@gmail.com"
- "root@wuvt.vt.edu"
- "wuvt@mutantmonkey.in"
command:
- "/usr/local/bin/ircalert"
- "-nick"
- "wuvt-ircalert"
- "-server"
- "irc.oftc.net:6697"
- "-ssl"
- "-channel"
- "#wuvt"
- "-message"
- "Use of backup account by unexpected client"
