apiVersion: v1
kind: Pod
metadata:
  name: musicbrainz-redis-store
  labels:
    app: musicbrainz-redis-store
spec:
  containers:
  - name: redis
    image: redis:3.2-alpine
    args:
    - '--appendonly yes'
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: redis-data
      mountPath: /data
  volumes:
  - name: redis-data
    hostPath:
      path: /media/local-storage/musicbrainz-redis-store-data
