apiVersion: v1
kind: Pod
metadata:
  name: wuvt-site-redis-am
  labels:
    app: wuvt-site-redis
    instance: am
spec:
  containers:
  - name: redis
    image: redis:3.2-alpine
    args:
    - '/etc/redis/redis.conf'
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: redis-config
      mountPath: /etc/redis
      readOnly: true
    - name: redis-data
      mountPath: /data
  volumes:
  - name: redis-config
    secret:
      secretName: wuvt-site-redis-am
  - name: redis-data
    hostPath:
      path: /media/local-storage/wuvt-site-redis-am-data
