---
- name: Configure system hostname
  hostname:
    name: "{{ hostname }}"
  tags:
  - common

- name: Add FQDN entry to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ hostname }}"
    state: present
  tags:
  - common
