---
- name: Install ceph repo
  copy: src=ceph-deploy.repo dest=/etc/yum.repos.d/ceph-deploy.repo
  tags:
  - repo
  - packages

- name: Install ceph-deploy
  yum: state=latest pkg=ceph-deploy
  tags:
    - packages

- name: Creates ceph config directory
  file: path=/etc/ceph-deploy/ state=directory

- stat: path=/etc/ceph-deploy/ceph.mon.keyring
  register: ceph_keyring

- name: Create initial config
  command: chdir=/etc/ceph-deploy ceph-deploy new {{ ansible_fqdn }}
  when: ceph_keyring.stat.exists == False

- name: Modify ceph.conf for single replica
  lineinfile: dest=/etc/ceph-deploy/ceph.conf line="osd pool default size = 1" regexp='^osd pool default size ='

- name: Modify ceph.conf for single node
  lineinfile: dest=/etc/ceph-deploy/ceph.conf line="osd crush chooseleaf type = 0" regexp='^osd crush chooseleaf type ='

- name: Install ceph locally
  command: chdir=/etc/ceph-deploy ceph-deploy install {{ ansible_fqdn }}

- name: Install ceph admin tools
  command: chdir=/etc/ceph-deploy ceph-deploy admin {{ ansible_fqdn }}

- name: Create initial mon config
  command: chdir=/etc/ceph-deploy ceph-deploy mon create-initial 

- name: Check if the osd was setup
  shell: ceph-deploy osd list {{ ansible_fqdn }} 2>&1 | grep /var/ceph-storage
  args:
    chdir: /etc/ceph-deploy 
  register: ceph_osd
  failed_when: 1 != 1
  
- name: Create ceph data directory
  file: path=/var/ceph-storage/ owner=ceph group=ceph state=directory
  when: ceph_osd.rc != 0

- name: Prepare file osd
  command: chdir=/etc/ceph-deploy ceph-deploy osd prepare {{ ansible_fqdn }}:/var/ceph-storage/
  when: ceph_osd.rc != 0

- name: Activate file osd
  command: chdir=/etc/ceph-deploy ceph-deploy osd activate {{ ansible_fqdn }}:/var/ceph-storage/
  when: ceph_osd.rc != 0

- name: Activate file osd
  command: chdir=/etc/ceph-deploy ceph-deploy osd activate {{ ansible_fqdn }}:/var/ceph-storage/
  when: ceph_osd.rc != 0

- name: Enable cephfs
  command: chdir=/etc/ceph-deploy ceph-deploy mds create {{ ansible_fqdn }}
