pki_dir: files/pki/
cfssl_endpoint: https://diginotar.wuvt.vt.edu:8888
cfssl_endpoint_ca: files/cfssl_ca.pem
cfssl_request:
  CN: kubelet
  key:
    algo: rsa
    size: 4096
  hosts: "{{ cfssl_hosts }}"

etcd_endpoints: https://192.168.0.157:2379,https://192.168.0.159:2379,https://192.168.0.237:2379,https://192.168.0.238:2379,https://192.168.0.243:2379

kube_container_runtime: docker
kube_controller_endpoint: https://192.168.0.246:443
kube_pod_network: 10.1.0.0/16
