---
- name: Apt update
  apt: update_cache=yes upgrade=yes
  tags:
  - apt
  - packages

- name: Install automation packages
  apt: name={{ item }} state=latest
  with_items:
  - alsa-utils
  - liquidsoap
  - liquidsoap-mode
  - liquidsoap-plugin-all
  - python3
  - python3-requests
  - socat
  tags:
  - packages

- name: Make sure pulseaudio and liquidsoap opus plugins are not installed
  apt: name={{ item }} state=absent
  with_items:
  - pulseaudio
  - pulseaudio-module-x11
  - liquidsoap-plugin-opus
  tags:
  - packages
