- name: Install stream-generator.service
  copy:
    src: stream-generator.service
    dest: /etc/systemd/system/stream-generator.service

- name: Install stream-generator config
  template:
    src: stream-generator.j2
    dest: /etc/default/stream-generator

- name: Reload services daemon
  command: systemctl daemon-reload

- name: Enable stream-generator service
  command: systemctl enable stream-generator

- name: (Re)start stream-generator service
  command: systemctl restart stream-generator
