---
- name: Install sssd packages
  apt:
    name:
    - sssd
    - libnss-sss
    - libpam-sss
    state: present
  tags:
  - packages

- name: Remove old LDAP packages
  apt:
    name:
    - libnss-ldap
    - libpam-ldap
    - nslcd
    - nslcd-utils
    state: present
  tags:
  - packages

- name: Install /etc/sssd
  file:
    dest: /etc/sssd
    mode: '0711'

- name: Install /etc/ldap/ldap.conf
  copy:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf
