---
- name: Stop and disable nscd
  service: name=nscd state=stopped enabled=no
  ignore_errors: yes
  when: ansible_os_family == "RedHat"
  tags: [auth]

- include_tasks: centos.yml
  when: ansible_os_family == "RedHat"
  tags: [auth]

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: [auth]

- name: Add the sudoers group to allowed sudoers
  copy: src=sudoers.d/01_sudoers dest=/etc/sudoers.d/01_sudoers
  tags: [auth]

- import_tasks: sshd.yml
