---
- name: Install ipa-client
  apt: name=freeipa-client state=present
  tags: [auth]

- name: Install autofs
  apt: name=autofs state=present

- name: Join freeipa domain
  tags: [auth]
  command: >
    ipa-client-install --enable-dns-updates --domain=wuvt.vt.edu
    --server=zolitude.wuvt.vt.edu -p joinaccount@WUVT.VT.EDU
    -w {{ joindomain_password }} -U
  args:
    creates: /etc/krb5.keytab
  when: joindomain_password is defined

# Note this only works if the old auth has been removed from sssd.conf
- name: Check if automount is configured
  register: automount_nss
  failed_when: automount_nss.rc == 254
  shell: /bin/grep automount /etc/nsswitch.conf
  tags: [auth]

- name: Add automount line to nsswitch
  lineinfile: dest=/etc/nsswitch.conf line="automount:{{ ' ' }} sss" regexp='^automount:.*$' state=present
  tags: [auth]

- name: Configure autofs mounts
  tags: [auth]
  when: automount_nss.rc != 0
  command: ipa-client-automount -U
  register: command_result
  failed_when:
  - "'already configured' not in command_result.stderr"
  - "command_result.rc != 0"

# Ubuntu does not package gssproxy, so we cannot use the kernel keyring for the
# ccache.  We remove the line so it will default to using the FILE ccache.
- name: Remove keyring line
  lineinfile: dest=/etc/krb5.conf regexp=".*default_ccache_name.*" state=absent
  tags: [auth]

- name: Install autofs.service
  copy:
    src: systemd/system/autofs.service
    dest: /etc/systemd/system/autofs.service
  tags:
  - auth

- name: Install sssd.service
  copy:
    src: systemd/system/sssd.service
    dest: /etc/systemd/system/autofs.service
  tags:
    auth

- name: Restart rpc-gssd
  service: name=rpc-gssd state=restarted
  tags: [auth]

- name: Restart autofs
  service: name=autofs state=restarted
  tags: [auth]

- name: Restart sssd
  service: name=sssd state=restarted
  tags: [auth]
