---
- name: Install ipa-client
  apt:
    name: freeipa-client
    state: present
  tags:
  - auth
  - packages

- name: Install chrony
  apt:
    name: chrony
    state: present
  tags:
  - auth
  - packages

- name: Set up chronyd.service alias because FreeIPA is buggy garbage
  file:
    src: /usr/lib/systemd/system/chrony.service
    dest: /etc/systemd/system/chronyd.service
    state: link
  tags:
  - auth

- name: Install gssproxy
  apt:
    name: gssproxy
    state: present
  tags:
  - auth
  - packages

- name: Install autofs
  apt:
    name: autofs
    state: present
  when: ipa_enable_automount
  tags:
  - autofs
  - packages

- name: Join freeipa domain (with mkhomedir)
  command: >
    ipa-client-install --enable-dns-updates --domain={{ ipa_server }}
    --server={{ ipa_server }} -p {{ ipa_joinaccount }}
    -w {{ joindomain_password }} -U --mkhomedir
  args:
    creates: /etc/krb5.keytab
  when: joindomain_password is defined and ipa_enable_automount
  tags:
  - auth

- name: Join freeipa domain (without mkhomedir)
  command: >
    ipa-client-install --enable-dns-updates --domain={{ ipa_server }}
    --server={{ ipa_server }} -p {{ ipa_joinaccount }}
    -w {{ joindomain_password }} -U
  args:
    creates: /etc/krb5.keytab
  when: joindomain_password is defined and not ipa_enable_automount
  tags:
  - auth

# Note this only works if the old auth has been removed from sssd.conf
- name: Check if automount is configured
  shell: /bin/grep automount /etc/nsswitch.conf
  register: automount_nss
  failed_when: automount_nss.rc == 254
  when: ipa_enable_automount
  tags:
  - autofs

- name: Add automount line to nsswitch
  lineinfile:
    dest: /etc/nsswitch.conf
    line: "automount:{{ ' ' }} sss"
    regexp: '^automount:.*$'
    state: present
  when: ipa_enable_automount
  tags:
  - autofs

# FIXME
- name: Configure autofs mounts
  when: "'rc' in automount_nss and automount_nss.rc != 0"
  command: ipa-client-automount -U
  register: command_result
  failed_when:
  - "'already configured' not in command_result.stderr"
  - "command_result.rc != 0"
  when: ipa_enable_automount
  tags:
  - autofs

# Ubuntu 16.04 does not package gssproxy, so we cannot use the kernel keyring
# for the ccache.  We remove the line so it will default to using the FILE
# ccache.
- name: Remove keyring line
  lineinfile:
    dest: /etc/krb5.conf
    regexp: ".*default_ccache_name.*"
    state: absent
  when: ansible_distribution_version == "16.04"
  tags:
  - auth

- name: Install autofs.service
  copy:
    src: systemd/system/autofs.service
    dest: /etc/systemd/system/autofs.service
  when: ipa_enable_automount
  tags:
  - autofs

- name: Install sssd.service
  copy:
    src: systemd/system/sssd.service
    dest: /etc/systemd/system/sssd.service
  tags:
  - auth

- name: Restart rpc-gssd
  service:
    name: rpc-gssd
    state: restarted
  tags:
  - auth

- name: Restart autofs
  service:
    name: autofs
    state: restarted
  when: ipa_enable_automount
  tags:
  - autofs

- name: Restart sssd
  service:
    name: sssd
    state: restarted
  tags:
  - auth
