---
- name: install certbot (apt)
  apt:
    name: certbot
    state: present
  when: ansible_pkg_mgr == "apt"
  tags: packages

- name: install certbot (yum)
  yum:
    name: certbot
    state: present
  when: ansible_pkg_mgr == "yum"
  tags: packages

- name: create /etc/letsencrypt
  file:
    dest: /etc/letsencrypt
    state: directory

- name: install /etc/letsencrypt/cli.ini
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini

- name: create /var/lib/letsencrypt/public_html
  file:
    dest: /var/lib/letsencrypt/public_html
    state: directory

- name: install systemd units
  copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/{{ item }}
  with_items:
  - letsencrypt-renewer.service
  - letsencrypt-renewer.timer
