---
- import_tasks: noselinux.yml
- import_tasks: packages.yml

- include_tasks: hostname.yml
  when: hostname is defined

- import_tasks: yum.yml
- import_tasks: mail.yml

- include_tasks: iptables.yml
  when: ansible_distribution_version.split(".")[0] == "6"
