---
- name: Download EPEL package for CentOS 6
  get_url: url=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6.8.noarch.rpm mode=0400
  when: ansible_distribution_version.split(".")[0] == "6"
#  when: ansible_distribution_major_version == "6"
  tags:
  - common

- name: Enable EPEL - CentOS 6
  command: rpm -Uvh /tmp/epel-release-6.8.noarch.rpm creates=/etc/yum.repos.d/epel.repo
#  when: ansible_distribution_major_version == "6"
  when: ansible_distribution_version.split(".")[0] == "6"
  tags:
  - common

- name: Enable EPEL - CentOS 7
  yum: name=epel-release state=present
  when: ansible_distribution_version.split(".")[0] == "7"
#  when: ansible_distribution_major_version == "7"
  tags:
  - common

- name: Import EPEL signing key - CentOS 7
  rpm_key: key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  when: ansible_distribution_version.split(".")[0] == "7"
#  when: ansible_distribution_major_version == "7"
  tags:
  - common

- name: Install common packages
  yum:
    name:
    # XXX: apparently yum-cron conflicts with yum? disabled until we figure this out
    #- yum-cron
    - smartmontools
    - emacs-nox
    - elinks
    - git
    - git-svn
    - htop
    - lsof
    - lynx
    - man
    - mosh
    - mtr
    - nmap
    - ncdu
    - net-tools
    - vim
    - rsync
    - screen
    - subversion
    - tmux
    - wget
    - zsh
    - pciutils
    - bind-utils
    - bash-completion
    - ntp
    - ntpdate
    - ntp-doc
    - weechat
    - weechat-devel
    - nfs-utils
    state: present
  tags:
  - packages
  - common

- name: Install packages for development
  yum:
    name:
    - gcc
    - make
    - openmpi
    - openmpi-devel
    - ruby
    - autoconf
    - automake
    - bison
    - byacc
    - cscope
    - ctags
    - diffstat
    - doxygen
    - elfutils
    - flex
    - gcc-c++
    - indent
    - intltool
    - libtool
    - patch
    - patchutils
    - rcs
    - redhat-rpm-config
    - rpm-build
    - swig
    - systemtap
    - unzip
    - zip
    - libselinux-python
    state: present
  tags:
  - packages
  - common
