---
- include_tasks: centos.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: systemd.yml
  when: ansible_service_mgr == 'systemd'
