---
- name: Restart ntp (Debian family)
  service:
    name: ntp
    state: restarted

- name: Restart ntpd (RedHat family)
  service:
    name: ntpd
    state: restarted

- name: Restart systemd-journald
  service:
    name: systemd-journald
    state: restarted
