kubernetes_worker_files:
- filesystem: root
  path: /etc/kubernetes/worker-kubeconfig.yaml
  mode: 420
  contents:
    source: "data:,{{ lookup('file', 'worker-kubeconfig.yaml') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/manifests/kube-proxy.yaml
  mode: 420
  contents:
    source: "data:,{{ lookup('template', 'kube-proxy.yaml.j2') | replace('\n', '\\n') }}"

kubernetes_worker_services:
- name: kubelet.service
  enable: true
  contents: "{{ lookup('template', 'kubelet.service.j2') | replace('\n', '\\n') }}"
