kubernetes_worker_files:
- filesystem: root
  path: /etc/kubernetes/worker-kubeconfig.yaml
  mode: 420
  contents:
    source: "data:,{{ lookup('template', 'worker-kubeconfig.yaml.j2') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/manifests/kube-proxy.yaml
  mode: 420
  contents:
    source: "data:,{{ lookup('template', 'kube-proxy.yaml.j2') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/worker.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/worker-key.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '-key.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/ca.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + 'ca.pem') | replace('\n', '\\n') }}"

kubernetes_worker_services:
- name: kubelet.service
  enable: true
  contents: "{{ lookup('template', 'kubelet.service.j2') | replace('\n', '\\n') }}"
