- name: install mail-server packages
  yum: name={{ item }} state=present
  with_items:
          - dovecot
          - postfix
          - opendkim
          - s-nail
          - spamassassin
  tags:
          - packages
          - mail

