---
- name: Install ntp.conf (Debian family)
  template:
    src: templates/ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644
  notify: Restart ntp (Debian family)
  when: ansible_os_family == "Debian"
  tags:
  - common

- name: Enable and start ntp service
  service: name=ntp enabled=yes state=started
  when: ansible_os_family == "Debian"
  tags:
  - services
  - common

- name: Install ntp.conf (RedHat family)
  template:
    src: templates/ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644
  notify: Restart ntpd (RedHat family)
  when: ansible_os_family == "RedHat"
  tags:
  - common

- name: Enable and start ntpd service
  service: name=ntpd enabled=yes state=started
  when: ansible_os_family == "RedHat"
  tags:
  - services
  - common
