- name: Install Liquidsoap
  apt:
    name:
    - liquidsoap
    - liquidsoap-plugin-alsa
    - liquidsoap-plugin-flac

- include_tasks: ia.yml
  when: pgmcheck_upload_to_ia

- name: Create /opt/pgmcheck
  file:
    dest: /opt/pgmcheck
    state: directory

- name: Create pgmcheck data directories
  file:
    dest: "/var/pgmcheck/{{ item }}"
    owner: liquidsoap
    group: liquidsoap
    state: directory
  with_items:
  - current
  - staging

- name: Install pgmcheck.liq
  template:
    src: pgmcheck.liq.j2
    dest: /opt/pgmcheck/pgmcheck.liq

- name: Install pgmcheck_move.sh
  template:
    src: pgmcheck_move.sh.j2
    dest: /opt/pgmcheck/pgmcheck_move.sh
    mode: 0755

- name: Install pgmcheck service
  copy:
    src: pgmcheck.service
    dest: /etc/systemd/system/pgmcheck.service

- name: Start and enable pgmcheck service
  service:
    name: pgmcheck.service
    state: started
    enabled: true

- name: Install pgmcheck archive cronjob
  cron:
    name: pgmcheck archive
    user: liquidsoap
    minute: 5
    job: /opt/pgmcheck/pgmcheck_move.sh
    state: present
