- name: Install pgmcheck.service
  copy:
    src: pgmcheck.service
    dest: /etc/systemd/system/pgmcheck.service

- name: Install pgmcheck config
  template:
    src: pgmcheck.j2
    dest: /etc/default/pgmcheck
    mode: 0600

- name: Create pgmcheck data directories
  shell: |
    mkdir -p "/var/pgmcheck/{current,staging}"
    chmod 644 "/var/pgmcheck/{current,staging}"
  args:
    executable: /bin/bash

- name: Reload services daemon
  command: systemctl daemon-reload

- name: Enable pgmcheck service
  command: systemctl enable pgmcheck

- name: (Re)start pgmcheck service
  command: systemctl restart pgmcheck
