- name: Install Docker PGP key
  shell: |
    apt-get update
    apt-get -y install ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

- name: Add Docker repository
  shell: |
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian trixie stable" \
      > /etc/apt/sources.list.d/docker.list

- name: Install docker-ce
  shell: |
    apt-get update
    apt-get -y install docker-ce

- name: Enable docker service
  command: systemctl enable docker

- name: (Re)start docker service
  command: systemctl restart docker
