hypervisor: valdistava.wuvt.vt.edu
vcpu: 8
memory: 5120
hostname: churchrock
public_ipv4: 192.168.0.249

etcd_ca: "{{ lookup('file', pki_dir + 'ca.pem') }}"
etcd_cert: "{{ lookup('file', pki_dir + hostname + '.pem') }}"
etcd_key: "{{ lookup('file', pki_dir + hostname + '-key.pem') }}"

ignition_extra_files:
- filesystem: root
  path: /etc/kubernetes/ssl/worker.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/worker-key.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '-key.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/ca.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + 'ca.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/manifests/jira.yaml
  mode: 420
  contents:
    source: "data:,{{ lookup('file', 'kubernetes/manifests/jira.yaml') | replace('\n', '\\n') }}"
