hypervisor: lambianceplaza.wuvt.vt.edu
vcpu: 8
memory: 6144
hostname: columbia
public_ipv4: 192.168.0.248
locksmith_window_start: 'Sun 19:00'
locksmith_window_length: 1h

ignition_extra_services:
- name: media-local\x2dstorage.mount
  enable: true
  contents: "{{ lookup('file', 'media-local\\x2dstorage.mount') | replace('\n', '\\n') }}"
