hypervisor: dreyfus.wuvt.vt.edu
vcpu: 2
memory: 6144
hostname: harborcay
public_ipv4: 192.168.0.158

qemu_machine_type: ubuntu
qemu_emulator: /usr/bin/qemu-system-x86_64
qemu_user: libvirt-qemu
qemu_group: kvm
use_apt: true

ignition_extra_files:
- filesystem: root
  path: /etc/krb5.keytab
  mode: 384
  contents:
    source: "{{ lookup('ini', 'harborcay section=keytab file=secrets.ini') }}"
