hypervisor: lambianceplaza.wuvt.vt.edu
vcpu: 2
memory: 1024
hostname: hitomi
public_ipv4: 192.168.0.237

etcd_ca: "{{ lookup('file', pki_dir + 'ca.pem') }}"
etcd_cert: "{{ lookup('file', pki_dir + hostname + '.pem') }}"
etcd_key: "{{ lookup('file', pki_dir + hostname + '-key.pem') }}"

ignition_extra_files:
- filesystem: root
  path: /etc/krb5.keytab
  mode: 384
  contents:
    source: "{{ lookup('ini', 'hitomi section=keytab file=secrets.ini') }}"
