hypervisor: bhopal.wuvt.vt.edu
hostname: naro1
public_ipv4: 192.168.0.246

etcd_ca: "{{ lookup('file', pki_dir + 'ca.pem') }}"
etcd_cert: "{{ lookup('file', pki_dir + hostname + '.pem') }}"
etcd_key: "{{ lookup('file', pki_dir + hostname + '-key.pem') }}"

ignition_extra_files:
- filesystem: root
  path: /etc/kubernetes/ssl/apiserver.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/apiserver-key.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '-key.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/ca.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + 'ca.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubelog-filebeat/filebeat.yml
  mode: 420
  contents:
    source: "data:,{{ lookup('file', 'kubelog-filebeat/filebeat.yml') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubelog-filebeat/logstash.pem
  mode: 420
  contents:
    source: "data:,{{ lookup('file', 'kubelog-filebeat/logstash.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/manifests/kubelog-filebeat.yaml
  mode: 420
  contents:
    source: "data:,{{ lookup('file', 'kubernetes/manifests/kubelog-filebeat.yaml') | replace('\n', '\\n') }}"
