hypervisor: bhopal.wuvt.vt.edu
hostname: naro1
public_ipv4: 192.168.0.246

ignition_extra_files:
- filesystem: root
  path: /etc/kubernetes/ssl/apiserver.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/apiserver-key.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + hostname + '-key.pem') | replace('\n', '\\n') }}"
- filesystem: root
  path: /etc/kubernetes/ssl/ca.pem
  mode: 384
  contents:
    source: "data:,{{ lookup('file', pki_dir + 'ca.pem') | replace('\n', '\\n') }}"
