hypervisor: wuvt2017004.wuvt.vt.edu
vcpu: 2
memory: 1024
hostname: navstar7
public_ipv4: 192.168.0.167

use_ignition: false

qemu_machine_type: pc-q35-2.5
qemu_user: libvirt-qemu
qemu_group: kvm
use_apt: true

ignition_extra_files:
- filesystem: root
  path: /etc/krb5.keytab
  mode: 384
  contents:
    source: "{{ lookup('ini', 'navstar7 section=keytab file=secrets.ini') }}"
