hypervisor: wuvt2017009.wuvt.vt.edu
vcpu: 16
memory: 24576
hostname: nedelin

use_ignition: false

qemu_machine_type: pc-q35-2.5
qemu_user: libvirt-qemu
qemu_group: kvm
use_apt: true

ignition_extra_files:
- filesystem: root
  path: /etc/krb5.keytab
  mode: 384
  contents:
    source: "{{ lookup('ini', 'nedelin section=keytab file=secrets.ini') }}"
