hypervisor: dreyfus.wuvt.vt.edu
vcpu: 2
memory: 1024
hostname: royalplaza
public_ipv4: 192.168.0.159

qemu_machine_type: ubuntu
qemu_emulator: /usr/bin/qemu-system-x86_64
qemu_user: libvirt-qemu
qemu_group: kvm
use_apt: true

etcd_ca: "{{ lookup('file', pki_dir + 'ca.pem') }}"
etcd_cert: "{{ lookup('file', pki_dir + hostname + '.pem') }}"
etcd_key: "{{ lookup('file', pki_dir + hostname + '-key.pem') }}"

ignition_extra_files:
- filesystem: root
  path: /etc/krb5.keytab
  mode: 384
  contents:
    source: "{{ lookup('ini', 'royalplaza section=keytab file=secrets.ini') }}"
