- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

- include_tasks: osqueryd.yml
  when: osquery_secret is defined
