---
automation_alsa_output: 'plughw:CARD=USB,DEV=0'
automation_base_path: 'http://titanic.wuvt.vt.edu/automation'
automation_playlist_api_url: ''
automation_trackman_url: ''
automation_trackman_password: ''
