---
- name: Install nginx
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
  notify:
    - Refresh sources
    - Upgrade packages

- name: Install nginx default config
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify: Restart Nginx
