---
- import_tasks: nfs.yml
- import_tasks: packages.yml
- import_tasks: backports.yml
- import_tasks: packaging.yml

# https://unix.stackexchange.com/questions/209832/debian-systemd-network-online-target-not-working
- name: Install ifup-wait-all-auto.service
  copy: src=ifup-wait-all-auto.service
        dest=/etc/systemd/system/ifup-wait-all-auto.service

- name: Enable ifup-wait-all-auto.service
  service: name=ifup-wait-all-auto.service enabled=yes
