- name: Install NFS client utilities
  apt:
    name: nfs-common
    state: latest
  tags:
  - packages

#- name: Create ladmin
#  user: name=ladmin groups=root home=/local/ladmin
#  tags:
#  - local 
#
#- name: Set local home dir
#  file: path=/local/ladmin recurse=yes state=directory owner=ladmin
#  tags: 
#  - local

#- name: change /etc/fstab
#  mount: fstype=nfs name=/home src=192.168.0.55:/mnt/mckillican/home state=unmounted

#- name: Move user's home dir
#  user: name=ladmin home=/local/ladmin
#  tags:
#  - local
