---
- name: Install packages for development
  apt:
    name:
    - gcc
    - ruby
    - ansible
    - sshpass
    state: latest
  tags:
  - packages

- name: Install debian packaging tools
  apt:
    name:
    - build-essential
    - make
    - debhelper
    - dh-make
    - fakeroot
    state: latest
  tags:
  - packages
